test

diff --git a/.github/workflows/ctlog-sth.yml b/.github/workflows/ctlog-sth.yml
--- a/.github/workflows/ctlog-sth.yml
+++ b/.github/workflows/ctlog-sth.yml
@@ -57,8 +57,9 @@ jobs:
             echo "probe_status=failed" >> $GITHUB_OUTPUT
             exit 1
           fi
+          echo "probe_status=failed" >> $GITHUB_OUTPUT
   pager:
-    if: github.event.inputs.triggerPagerDutyTest=='true' || failure()
+    if: github.event.inputs.triggerPagerDutyTest=='true' || (failure() && needs.ctlog-sth.outputs.probe_status == "failed")
     needs: [ctlog-sth]
     uses: ./.github/workflows/reusable-pager.yml
     secrets:
