rename var

diff --git a/.github/workflows/reusable-prober.yml b/.github/workflows/reusable-prober.yml
--- a/.github/workflows/reusable-prober.yml
+++ b/.github/workflows/reusable-prober.yml
@@ -184,7 +184,7 @@ jobs:
     runs-on: ubuntu-latest
     outputs:
       rekor_fulcio_e2e: ${{ steps.msg.outputs.rekor_fulcio_e2e }}
-      oidc_server_availabe: ${{ steps.github-oidc-server.outputs.oidc_server_availabe }}
+      ignore_failure: ${{ steps.github-oidc-server.outputs.ignore_failure }}
     steps:
       - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
   
@@ -196,10 +196,12 @@ jobs:
         run: |
           curl -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" $ACTIONS_ID_TOKEN_REQUEST_URL&audience=sigstore
 
-      - name: Set oidc_server_availabe outputs
+      # Since the server is down, we want to ignore the failure in this workflow
+      # and skip paging PagerDuty
+      - name: Set ignore_failure outputs
         if: failure()
         run: |
-          echo "oidc_server_availabe=failure" >> $GITHUB_OUTPUT
+          echo "ignore_failure=true" >> $GITHUB_OUTPUT
 
       - uses: actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753 # v3.3.0
         id: setup-go
@@ -341,7 +343,7 @@ jobs:
           fi
 
   pagerduty-notification:
-    if: github.event.inputs.triggerPagerDutyTest=='true' || (failure() && ${{ needs.rekor-fulcio-e2e.outputs.oidc_server_availabe }} != 'failure')
+    if: github.event.inputs.triggerPagerDutyTest=='true' || (failure() && ${{ needs.rekor-fulcio-e2e.outputs.ignore_failure }} != 'true')
     needs: [sigstore-probe, root-probe, rekor-fulcio-e2e, compute-summary-msg]
     uses: ./.github/workflows/reusable-pager.yml
     secrets:
